### ISSUE TITLE
Add small effects on "Copy color" button inside color boxes.

### ISSUE THREAD

**Issue by Anjali2201** [KiranAminPanjwani/Randomized-Color-Lab#13]
Would like to add:
1. Change the cursor to pointer
2. Add hover box shadow effect 
3. Small transition

**Comment by KiranAminPanjwani** [comment]
Go for it! 🤩

**Comment by Vedant755** [comment]
Can I work on the issue as I have tackled similar kinds of stuff on my personal website too!
