### ISSUE TITLE
Enhance documentation of the code base

### ISSUE THREAD

**Issue by itsmdasifraza** [KiranAminPanjwani/Randomized-Color-Lab#14]
Wrong clone command mentioned for point 2, It must be:
git clone https://github.com/<your_user_name>/Randomized-Color-Lab.git

![Screenshot (195)](https://user-images.githubusercontent.com/58258334/193358262-78702936-7890-4f98-a02f-f283078b9360.png)

Point 5 and 6 got merged / overlapping

![Screenshot (196)](https://user-images.githubusercontent.com/58258334/193358519-71b0322b-9321-4da8-ae16-89cfb1b28b3a.png)

"npm install" command is missing

![Screenshot (197)](https://user-images.githubusercontent.com/58258334/193358678-e782564d-80d1-48a2-be87-d4f397604a85.png)

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead! 🤩
