### ISSUE TITLE
Add hand cursor to buttons

### ISSUE THREAD

**Issue by Dun-sin** [KiranAminPanjwani/Randomized-Color-Lab#18]
Related to issue #5 

All buttons should have the hand cursor to indicate they are clickable
For example: The `copy color` button
![image](https://user-images.githubusercontent.com/78784850/193362467-dc148855-0341-42a1-a0d6-6ca36da9b917.png)

**Comment by ahegde3** [comment]
Can I take up this issue?

**Comment by ahegde3** [comment]
PR :-https://github.com/KiranAminPanjwani/Randomized-Color-Lab/pull/25

**Comment by KiranAminPanjwani** [comment]
> Related to issue #5
> 
> All buttons should have the hand cursor to indicate they are clickable For example: The `copy color` button ![image](https://user-images.githubusercontent.com/78784850/193362467-dc148855-0341-42a1-a0d6-6ca36da9b917.png)
> 
> ### if it's fine can I work on this

Yes, sure! 🤩
