### ISSUE TITLE
Unnecessary gap

### ISSUE THREAD

**Issue by Dun-sin** [KiranAminPanjwani/Randomized-Color-Lab#19]
There's an unnecessary gap in between these two elements, it doesn't make things look good

I can work on it, if you feel this change is valid
![image](https://user-images.githubusercontent.com/78784850/193362644-9387740d-a043-420b-8d8a-194ede24b8a7.png)

**Comment by KiranAminPanjwani** [comment]
Actually, I have spaced them to create the design. But let me know if you can improve the design by applying another style. So I assign the problem to you. 😊
