### ISSUE TITLE
Fix broken color container code in the app main page

### ISSUE THREAD

**Issue by itsmdasifraza** [KiranAminPanjwani/Randomized-Color-Lab#2]
![Screenshot (192)](https://user-images.githubusercontent.com/58258334/193333537-377d60dc-ebc0-42b0-89aa-0cc0ba49a885.png)

**Comment by chandankumar1307** [comment]
Can you please describe the issue

**Comment by RahulSharma4329** [comment]
I assume that when page is loaded and new colour sare not generated at that time also the copy color buttons give false colour codes and that they has to be fixed.

I'd like to work on this issue please assign this to me .

**Comment by KiranAminPanjwani** [comment]
@itsmdasifraza Please provide a brief description of the changes you want to make. Thank you. 😊
