### ISSUE TITLE
Create an alert message

### ISSUE THREAD

**Issue by zugzwang03** [KiranAminPanjwani/Randomized-Color-Lab#20]
Although it is a game, but the part 'You lose' , 'You win' is not so articulately distinct. Adding an alert message in the top about winning or losing the game can make the whole process of judgement rather more distinct. 
I want to create some alert messages to be displayed on top so that the user gets it clear that the verdict has come.
Can I make this contribution under Hacktoberfest'22?

**Comment by KiranAminPanjwani** [comment]
Thank you for highlighting the bug.✨
But instead of adding an alert message, can you add an animation to the "you lose" and "you win" text to make a difference? 😊

**Comment by zugzwang03** [comment]
yeah fine, will do it once assigned!

**Comment by KiranAminPanjwani** [comment]
Okay, I'm Closing this one.
Please create a new issue for animation. Thank you. 😊✨
