### ISSUE TITLE
Copy color buttons shouldn't be able to hightlight

### ISSUE THREAD

**Issue by beam41** [KiranAminPanjwani/Randomized-Color-Lab#22]
![image](https://user-images.githubusercontent.com/1791353/193395789-9988035c-e8cd-4813-90e4-9aa6ce040638.png)

As general user interface rule button shouldn't be able to hightlight (like github 'comment' button). Can I fix them.

**Comment by KiranAminPanjwani** [comment]
Yeah sure, please go ahead! 🤩
