### ISSUE TITLE
Footer width is covering the main section

### ISSUE THREAD

**Issue by AadityaNitin** [KiranAminPanjwani/Randomized-Color-Lab#27]
![color lab](https://user-images.githubusercontent.com/81017088/193410910-33b7cc3c-f91c-4c11-8ece-ea05c726352d.png)

if this is a issue can I take it?

**Comment by piyush-panpaliya** [comment]
yes this is definitwly a bug

**Comment by AadityaNitin** [comment]
hey @KiranAminPanjwani could you kindly assign me this issue please?

**Comment by KiranAminPanjwani** [comment]
> ![color lab](https://user-images.githubusercontent.com/81017088/193410910-33b7cc3c-f91c-4c11-8ece-ea05c726352d.png)
> 
> if this is a issue can I take it?

Sure, please go ahead! 🤩

**Comment by AadityaNitin** [comment]
Fix: Footer overlapping the main section
@KiranAminPanjwani I have raised a PR #51 that will take care of the issue
