### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by Sir-Martin-Esq-III** [KiranAminPanjwani/Randomized-Color-Lab#33]
Another thing that should be added for a beginner react project is how to write unit tests for components correctly!

Can you please assign me to this issue, thanks

**Comment by KiranAminPanjwani** [comment]
Do you want to add the "unit tests" concept in Learn.md file?

**Comment by Sir-Martin-Esq-III** [comment]
I would actually write some unit tests & update the learn.md file

**Comment by KiranAminPanjwani** [comment]
> I would actually write some unit tests & update the learn.md file

Sure! 🤩
Please create a new issue for this. Thank you. 😊
