### ISSUE TITLE
Use Spacebar to get random color

### ISSUE THREAD

**Issue by sohan2503001** [KiranAminPanjwani/Randomized-Color-Lab#35]
1.It will be easy and fun to get random colors instead of clicking on it repeatedly.
2.we will use spacebar to generate random colors.

**Comment by Athi223** [comment]
Hey @KiranAminPanjwani, I'd like to work on this if its available for contribution

**Comment by KiranAminPanjwani** [comment]
> 1.It will be easy and fun to get random colors instead of clicking on it repeatedly. 2.we will use spacebar to generate random colors.

Yeah sure, go ahead! 🤩

**Comment by Athi223** [comment]
@KiranAminPanjwani Done! Please have a look
