### ISSUE TITLE
[FEATURE] Unit tests

### ISSUE THREAD

**Issue by Sir-Martin-Esq-III** [KiranAminPanjwani/Randomized-Color-Lab#38]
### Description

Add unit tests and documentation to the project.

Use jest and RTL to write unit tests and then explain about unit tests in the `learn.md` file

**Comment by KiranAminPanjwani** [comment]
Thank you for raising this issue. 😊
But I think unit testing is not needed here. Sorry for the inconvenience. 
Please look for other bugs or try to add a feature if possible. ✨
