### ISSUE TITLE
[FEATURE] Add a hover effect to squares to distinguish then better

### ISSUE THREAD

**Issue by jackwebdev** [KiranAminPanjwani/Randomized-Color-Lab#39]
### Description

It would be cool at add a 3D hover effect feature. Sometimes when you get whitish colours the border blends in too much. Also it adds some fun interaction. 

### Screenshots

![Screenshot 2022-10-01 at 6 08 29 pm](https://user-images.githubusercontent.com/33595694/193424720-9ede0b0c-5057-4c41-8e8d-bf063e30d5e0.png)

**Comment by KiranAminPanjwani** [comment]
Sure! 🤩

**Comment by jackwebdev** [comment]
Thank you! I have submitted my pull request. #41
