### ISSUE TITLE
Remove "code smells" from Home page

### ISSUE THREAD

**Issue by Sir-Martin-Esq-III** [KiranAminPanjwani/Randomized-Color-Lab#4]
Seeing as this is meant to be an application meant to teach beginners how to use React, it might be a good idea to remove some
"code smells". These include : 

- Ternary operators with an empty falsy value i.e `true?"its true":" "`
- When and when not to use the use effect hook

**Comment by Lofty-Brambles** [comment]
Hello, if this issue is open to being worked on, I'd love to work on it!

**Comment by Sir-Martin-Esq-III** [comment]
Please see the above PR & and the hacktoberfest tag to it
