### ISSUE TITLE
Changing the Button Style 

### ISSUE THREAD

**Issue by Akshun-01** [KiranAminPanjwani/Randomized-Color-Lab#42]
### Description

Hey, I think the generate color button should not cover the whole page width . rather it would look better if we style it as a button instead.Also in this way the 'End Game?' or basically the reset button can also be properly placed on screen in case the player gets the right color. 
If, u think this can be a possible feature to work on, please do assign me this issue.

### Screenshots

![Screenshot (227)](https://user-images.githubusercontent.com/93793691/193426262-b40ab65e-45c4-40af-92ef-11bfa6dcf633.png)

![Screenshot (228)](https://user-images.githubusercontent.com/93793691/193426592-7d423827-72a1-4ac4-bc99-99b80a8af335.png)

**Comment by KiranAminPanjwani** [comment]
Yeah sure, please go ahead! 🤩
