### ISSUE TITLE
Transition doesn't work on the squares

### ISSUE THREAD

**Issue by jackwebdev** [KiranAminPanjwani/Randomized-Color-Lab#43]
### Description

Hello,

I have added a bug fix pull request. The issue is relating to the hexcodes array map method and a new React Key being generated and resulting in a new element being generated. As this new Key is made React can't keep track of the element before resulting in the transition effect not applying.

The transitions do not apply when you generate new colours. Before and after below.

Fixed in #34.

### Broken Transition
https://user-images.githubusercontent.com/33595694/193428765-3cc77a81-7def-42ed-9250-8a9383d423a3.mov

### Fixed in Pull Request #34 
https://user-images.githubusercontent.com/33595694/193428770-18b5db12-8d33-45d4-8b3f-c76e9f375d66.mov

**Comment by aritroCoder** [comment]
I want ton work on this, can you please assign it to me?

**Comment by KiranAminPanjwani** [comment]
Okay, I will review it. Thank you. 🤩
