### ISSUE TITLE
Add editor files and  configuration to gitignore list

### ISSUE THREAD

**Issue by slim-codes** [KiranAminPanjwani/Randomized-Color-Lab#52]
### Description

Inlcude editor directories and files to prevent default editor configuration of contributors from clashing

### Screenshots

![Screenshot from 2022-10-02 12-32-51](https://user-images.githubusercontent.com/72257135/193451800-452165b6-5810-4f3c-a109-7b6b456fa9bf.png)

**Comment by KiranAminPanjwani** [comment]
No dear, I don't want to make changes. Thank you for highlighting this. 😊
Kindly find other bugs if possible. Or visit my other repo: https://github.com/KiranAminPanjwani/Work-Flash
