### ISSUE TITLE
[DOCS] Minor issues

### ISSUE THREAD

**Issue by slim-codes** [KiranAminPanjwani/Randomized-Color-Lab#54]
### Description

Under the **Contribution is fun** section, there's a paragraph that says "If you have any suggestions you can reach out to me".

- Consider stating the channels through which you can be reached out to in that section. This can be done by specifying your work email, twitter etc

- There are a few minor grammar fixes I have proposed in the PR that's linked to this issue

**Comment by KiranAminPanjwani** [comment]
Thank you so much for highlighting this issue! 🤩
