### ISSUE TITLE
Change language from JavaScript to TypeScript

### ISSUE THREAD

**Issue by beam41** [KiranAminPanjwani/Randomized-Color-Lab#6]
Use TypeScript for type safety and better code hinting

**Comment by codingmickey** [comment]
I have some experience with typescript in nodejs not in React, can I try this out?

**Comment by astro3012** [comment]
I've been working exclusively on a TS+React stack. Mind If I take a go at this?

**Comment by KiranAminPanjwani** [comment]
No dear, I don't want to make changes. Try to find other bugs if possible. 😊
Or visit my other repo: https://github.com/KiranAminPanjwani/Work-Flash
