### ISSUE TITLE
[FEATURE] <description> Copy the generated color hex code on clipboard

### ISSUE THREAD

**Issue by kunaaal13** [KiranAminPanjwani/Randomized-Color-Lab#61]
### 🎇 Description

An enhancement so that we can copy the generated hex code of the color to the clipboard. I want to work on this enhancement

**Comment by KiranAminPanjwani** [comment]
This feature is already available. 

![image](https://user-images.githubusercontent.com/90326051/193587595-1f472f0b-bb01-47ca-8863-271b0c549852.png)
