### ISSUE TITLE
Hover state for color squares should only apply to desktop viewports

### ISSUE THREAD

**Issue by tes-balo** [KiranAminPanjwani/Randomized-Color-Lab#64]
### 🎇 Description

I noticed that the **hover** state only applies for mobile screen sizes. This is not ideal
- It's not recommended to use hover state for mobile devices. Use a **ripple effect** instead on mobile screens
- hover state should be present on **desktop** view only

### 📷 Screenshots

https://user-images.githubusercontent.com/72257135/193664186-de77f145-d004-4b54-a36b-80ee7433bb13.mp4

![Screenshot from 2022-10-03 20-30-05](https://user-images.githubusercontent.com/72257135/193664572-e7bbca55-58b1-4c0b-a369-2af9ef5502eb.png)

**Comment by sushantgwr87** [comment]
Can I work on this under Hactoberfest?

**Comment by slim-codes** [comment]
@KiranAminPanjwani Working on it

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani Working on it

Thank you for highlighting the issue, please go ahead! 🤩
