### ISSUE TITLE
Color tile transition effect

### ISSUE THREAD

**Issue by ahegde3** [KiranAminPanjwani/Randomized-Color-Lab#68]
### 🎇 Description

On mouse hover the color tile show a transition

**Comment by KiranAminPanjwani** [comment]
Can you please share an example? 😊

**Comment by KiranAminPanjwani** [comment]
You can also visit my other repos:

https://github.com/KiranAminPanjwani/Work-Flash

https://github.com/KiranAminPanjwani/LeatherHoard
