### ISSUE TITLE
[BUG] Prettier config is empty

### ISSUE THREAD

**Issue by slim-codes** [KiranAminPanjwani/Randomized-Color-Lab#71]
### 🎇 Description

- The prettier file is empty and as such the associated files are not getting formatted prior to committing.

- Even though **Husky** has been configured, a contributor should be able to use the specified config for previewing their formatted changes. This is only possible via a locally configured prettier config.

- The main purpose of **Husky** is to ensure that the appropriate formating is done when a contributor forgets to format their changes with Prettier or refuses to.

### 📷 Screenshots

![Screenshot from 2022-10-06 23-30-33](https://user-images.githubusercontent.com/72257135/194430385-433dadc9-683f-490d-bf3d-dc155b4c949f.png)

**Comment by KiranAminPanjwani** [comment]
Sorry dear, I don't want to make changes to it. Please try to find other bugs or issues.
You can also visit my other repos:

https://github.com/KiranAminPanjwani/Work-Flash

https://github.com/KiranAminPanjwani/LeatherHoard
