### ISSUE TITLE
UI/Color of the website 

### ISSUE THREAD

**Issue by heyvats21** [KiranAminPanjwani/Randomized-Color-Lab#72]
### 🎇 Description

The black color and it shades does not look nice in the randomized-color-lab webapp . 

### 📷 Screenshots

![image](https://user-images.githubusercontent.com/81029204/194613925-7c670e01-df77-4eea-8509-6fb5f92fea89.png)

**Comment by tanishk-23** [comment]
@heyvats21 Can you please assign this issue to me?

**Comment by KiranAminPanjwani** [comment]
Sorry dear, I don't want to make changes to it. Please try to find other bugs or issues.
You can also visit my other repos: 

https://github.com/KiranAminPanjwani/Work-Flash

https://github.com/KiranAminPanjwani/LeatherHoard
