### ISSUE TITLE
[BUG] Clearer text

### ISSUE THREAD

**Issue by Dun-sin** [KiranAminPanjwani/Randomized-Color-Lab#75]
### 🎇 Description

The colour of the footer isn't really visible, don't know if this is intentional

### 📷 Screenshots

![image](https://user-images.githubusercontent.com/78784850/195069253-190acac0-cdc4-4a8c-aa64-3419beeb25b1.png)

**Comment by KiranAminPanjwani** [comment]
Please make the text color slightly lighter. It should not be too bright.
